name: disabled-jekyll

on:
  # Keep only manual trigger so it doesn't run on push
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Jekyll workflow disabled for this repo"
