# Simple workflow for deploying static content to GitHub Pages
name: disabled-static

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Static workflow disabled for this repo"
